name: Challenging Rails

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Challenging Rails
    runs-on: ubuntu-26.04
    services:
      postgres:
        image: postgres:18.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      CI: true
      RAILS_ENV: test
      POSTGRES_HOST_TEST: localhost
      POSTGRES_PORT_TEST: 5432
      POSTGRES_USERNAME_TEST: postgres_user
      POSTGRES_PASSWORD_TEST: postgres_password
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v7
    - name: 必要なパッケージをインストールする
      run: |
        sudo apt install fonts-migmix
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@e81a8fa391b11a595c1b7ed84177cc0fe02faf83 # v1.328.0
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: （予定地）Node.js のセットアップを行う
      run: |
        echo '（予定地）Node.js のセットアップを行う'
    - name: データベースをセットアップする
      run: |
        bin/rails db:prepare
    - name: RSpec を実行する
      run: |
        bundle exec rspec
    - name: tmp/screenshots のアーティファクトをアップロードする
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: screenshots
        path: tmp/screenshots
    - name: tmp/capybara のアーティファクトをアップロードする
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: capybara
        path: tmp/capybara
